### ISSUE TITLE
Fix for workspaceFolder path

### ISSUE THREAD

**Issue by LukaDev7** [angelina-tsuboi/duck-duck-boom#2]
Use workspace.workspaceFolders[0]?.uri.fsPath and not workspace.workspaceFolders[0]?.uri.toString() to get the extension working again :)

**Comment by ANG13T** [comment]
@LukaDev7 Thanks so much! Could you possibly submit a PR with the changes? I haven't looked at the code for this project in ages, so that would be so helpful!

**Comment by LukaDev7** [comment]
I will send a pr quite soon

**Comment by LukaDev7** [comment]
Pull request done!
